using DWIS.API.DTO;
using DWIS.RigOS.Common.Worker;
using DWIS.Vocabulary.Schemas;
using OSDC.DotnetLibraries.Drilling.DrillingProperties;
using OSDC.UnitConversion.Conversion;
using OSDC.UnitConversion.Conversion.DrillingEngineering;
using System.Reflection;

namespace DWIS.DAQBridge.BaraLogix.OPCUASink
{
    public class ActivePitOutputData : DWISData
    {
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, Dictionary<string, QuerySpecification>>> LocalSparQLQueries = new(BuildSparQLQueries(typeof(ActivePitOutputData)));
        private static readonly Lazy<IReadOnlyDictionary<PropertyInfo, ManifestFile>> LocalManifests = new(BuildManifests(typeof(ActivePitOutputData), "BaraLogixDataManifest", "Halliburton", "DWISBridge"));
        public override Lazy<IReadOnlyDictionary<PropertyInfo, Dictionary<string, QuerySpecification>>> SparQLQueries { get => LocalSparQLQueries; }
        public override Lazy<IReadOnlyDictionary<PropertyInfo, ManifestFile>> Manifests { get => LocalManifests; }

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaraLogixAtActivePitMeasuredTemperature")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.HasDynamicValue, "BaraLogixAtActivePitMeasuredTemperature")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("topSideTelemetry", Nouns.Enum.TopSideTelemetry)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsTransmittedBy, "topSideTelemetry")]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredTemperature", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredTemperature")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaraLogixAtActivePitMeasuredTemperature#01")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.HasUncertaintyMean, "BaraLogixAtActivePitMeasuredTemperature#01")]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.MeasurementDevice)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.HydraulicLogicalElement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("ActivePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Verbs.Enum.IsHydraulicConnectedTo, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Baroid#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsProvidedBy, "Baroid#01")]
        public ScalarProperty? MeasuredTemperature { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaraLogixAtActivePitMeasuredPressure")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.HasDynamicValue, "BaraLogixAtActivePitMeasuredPressure")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("topSideTelemetry", Nouns.Enum.TopSideTelemetry)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsTransmittedBy, "topSideTelemetry")]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredPressure", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredPressure")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaraLogixAtActivePitMeasuredPressure#01")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.HasUncertaintyMean, "BaraLogixAtActivePitMeasuredPressure#01")]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.MeasurementDevice)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.HydraulicLogicalElement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("ActivePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Verbs.Enum.IsHydraulicConnectedTo, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Baroid#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsProvidedBy, "Baroid#01")]
        public ScalarProperty? MeasuredPressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaraLogixAtActivePitDensityCoriolisFlowmeter")]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Nouns.Enum.DerivedMeasurement)]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.HasDynamicValue, "BaraLogixAtActivePitDensityCoriolisFlowmeter")]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.MassDensityDrilling)]
        [SemanticFact("topSideTelemetry", Nouns.Enum.TopSideTelemetry)]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.IsTransmittedBy, "topSideTelemetry")]
        [SemanticFact("MovingAverageBaraLogixAtActivePitDensityCoriolisFlowmeter", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitDensityCoriolisFlowmeter")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitDensityCoriolisFlowmeter#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaraLogixAtActivePitDensityCoriolisFlowmeter#01")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.HasUncertaintyMean, "BaraLogixAtActivePitDensityCoriolisFlowmeter#01")]
        [SemanticFact("VibratingTubeCoriolisFlowmeterPrinciple", Nouns.Enum.ResonantMeasurementPrinciple)]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.UsesMeasurementPrinciple, "VibratingTubeCoriolisFlowmeterPrinciple")]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.MeasurementDevice)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.HydraulicLogicalElement)]
        [SemanticFact("ActivePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Verbs.Enum.IsHydraulicConnectedTo, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredTemperature", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredTemperature")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.HasTemperatureReference, "BaraLogixAtActivePitMeasuredTemperature#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredPressure", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredPressure")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.HasPressureReference, "BaraLogixAtActivePitMeasuredPressure#01")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Baroid#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaraLogixAtActivePitDensityCoriolisFlowmeter#01", Verbs.Enum.IsProvidedBy, "Baroid#01")]
        public ScalarProperty? MassDensityFromCoriolisAtMeasuredTemperatureAndPressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticStringVariable("BaraLogixAtActivePitFlowCurveAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Nouns.Enum.DirectMeasurement)]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Nouns.Enum.JSonDataType)]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Nouns.Enum.FlowCurve)]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Verbs.Enum.HasDynamicValue, "BaraLogixAtActivePitFlowCurveAtMeasuredTP")]
        [SemanticFact("topSideTelemetry", Nouns.Enum.TopSideTelemetry)]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Verbs.Enum.IsTransmittedBy, "topSideTelemetry")]
        [SemanticFact("MovingAverageBaraLogixAtActivePitFlowCurveAtMeasuredTP", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitFlowCurveAtMeasuredTP")]
        [SemanticFact("concentricCylindersMeasurementPrinciple", Nouns.Enum.ConcentricCylindersMeasurementPrinciple)]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Verbs.Enum.UsesMeasurementPrinciple, "concentricCylindersMeasurementPrinciple")]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.MeasurementDevice)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.HydraulicLogicalElement)]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("ActivePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Verbs.Enum.IsHydraulicConnectedTo, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredTemperature", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredTemperature")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Verbs.Enum.HasTemperatureReference, "BaraLogixAtActivePitMeasuredTemperature#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredPressure", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredPressure")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Verbs.Enum.HasPressureReference, "BaraLogixAtActivePitMeasuredPressure#01")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Baroid#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaraLogixAtActivePitFlowCurveAtMeasuredTP#01", Verbs.Enum.IsProvidedBy, "Baroid#01")]
        public FlowCurve? FlowCurveAtMeasuredTemperatureAndPressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Nouns.Enum.ComputedData)]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.HasDynamicValue, "BaraLogixAtActivePitPlasticViscosityAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.DynamicViscosityDrilling)]
        [SemanticFact("topSideTelemetry", Nouns.Enum.TopSideTelemetry)]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.IsTransmittedBy, "topSideTelemetry")]
        [SemanticFact("MovingAverageBaraLogixAtActivePitPlasticViscosityAtMeasuredTP", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitPlasticViscosityAtMeasuredTP")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.HasUncertaintyMean, "BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01")]
        [SemanticFact("binghamPlastic", Nouns.Enum.BinghamPlastic)]
        [SemanticFact("binghamPlastic", Verbs.Enum.HasPlasticViscosity, "BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01")]
        [SemanticFact("concentricCylindersMeasurementPrinciple", Nouns.Enum.ConcentricCylindersMeasurementPrinciple)]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.UsesMeasurementPrinciple, "concentricCylindersMeasurementPrinciple")]
        [SemanticFact("BaraLogixAtActivePitBinghamPlasticModelFitter#01", Nouns.Enum.ModelFitter)]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.IsComputedBy, "BaraLogixAtActivePitBinghamPlasticModelFitter#01")]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.MeasurementDevice)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.HydraulicLogicalElement)]
        [SemanticFact("BaraLogixAtActivePitBinghamPlasticModelFitter#01", Verbs.Enum.IsSubSystemOf, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("ActivePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Verbs.Enum.IsHydraulicConnectedTo, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredTemperature", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredTemperature")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.HasTemperatureReference, "BaraLogixAtActivePitMeasuredTemperature#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredPressure", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredPressure")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.HasPressureReference, "BaraLogixAtActivePitMeasuredPressure#01")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Baroid#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaraLogixAtActivePitPlasticViscosityAtMeasuredTP#01", Verbs.Enum.IsProvidedBy, "Baroid#01")]
        public ScalarProperty? PlasticViscosityAtMeasuredTemperatureAndPressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaraLogixAtActivePitYieldPointAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Nouns.Enum.ComputedData)]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.HasDynamicValue, "BaraLogixAtActivePitYieldPointAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.FluidShearStress)]
        [SemanticFact("topSideTelemetry", Nouns.Enum.TopSideTelemetry)]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.IsTransmittedBy, "topSideTelemetry")]
        [SemanticFact("MovingAverageBaraLogixAtActivePitYieldPointAtMeasuredTP", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitYieldPointAtMeasuredTP")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitYieldPointAtMeasuredTP#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaraLogixAtActivePitYieldPointAtMeasuredTP#01")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.HasUncertaintyMean, "BaraLogixAtActivePitYieldPointAtMeasuredTP#01")]
        [SemanticFact("binghamPlastic", Nouns.Enum.BinghamPlastic)]
        [SemanticFact("binghamPlastic", Verbs.Enum.HasYieldPoint, "BaraLogixAtActivePitYieldPointAtMeasuredTP#01")]
        [SemanticFact("concentricCylindersMeasurementPrinciple", Nouns.Enum.ConcentricCylindersMeasurementPrinciple)]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.UsesMeasurementPrinciple, "concentricCylindersMeasurementPrinciple")]
        [SemanticFact("BaraLogixAtActivePitBinghamPlasticModelFitter#01", Nouns.Enum.ModelFitter)]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.IsComputedBy, "BaraLogixAtActivePitBinghamPlasticModelFitter#01")]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.MeasurementDevice)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.HydraulicLogicalElement)]
        [SemanticFact("BaraLogixAtActivePitBinghamPlasticModelFitter#01", Verbs.Enum.IsSubSystemOf, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("ActivePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Verbs.Enum.IsHydraulicConnectedTo, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredTemperature", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredTemperature")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.HasTemperatureReference, "BaraLogixAtActivePitMeasuredTemperature#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredPressure", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredPressure")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.HasPressureReference, "BaraLogixAtActivePitMeasuredPressure#01")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Baroid#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaraLogixAtActivePitYieldPointAtMeasuredTP#01", Verbs.Enum.IsProvidedBy, "Baroid#01")]
        public ScalarProperty? YieldPointAtMeasuredTemperatureAndPressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Nouns.Enum.ComputedData)]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.HasDynamicValue, "BaraLogixAtActivePitYPLYieldStressAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.FluidShearStress)]
        [SemanticFact("topSideTelemetry", Nouns.Enum.TopSideTelemetry)]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.IsTransmittedBy, "topSideTelemetry")]
        [SemanticFact("MovingAverageBaraLogixAtActivePitYPLYieldStressAtMeasuredTP", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitYPLYieldStressAtMeasuredTP")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.HasUncertaintyMean, "BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01")]
        [SemanticFact("YPL", Nouns.Enum.YieldPowerLaw)]
        [SemanticFact("YPL", Verbs.Enum.HasYieldStress, "BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01")]
        [SemanticFact("concentricCylindersMeasurementPrinciple", Nouns.Enum.ConcentricCylindersMeasurementPrinciple)]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.UsesMeasurementPrinciple, "concentricCylindersMeasurementPrinciple")]
        [SemanticFact("BaraLogixAtActivePitYPLModelFitter#01", Nouns.Enum.ModelFitter)]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.IsComputedBy, "BaraLogixAtActivePitYPLModelFitter#01")]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.MeasurementDevice)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.HydraulicLogicalElement)]
        [SemanticFact("BaraLogixAtActivePitYPLModelFitter#01", Verbs.Enum.IsSubSystemOf, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("ActivePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Verbs.Enum.IsHydraulicConnectedTo, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredTemperature", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredTemperature")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.HasTemperatureReference, "BaraLogixAtActivePitMeasuredTemperature#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredPressure", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredPressure")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.HasPressureReference, "BaraLogixAtActivePitMeasuredPressure#01")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Baroid#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaraLogixAtActivePitYPLYieldStressAtMeasuredTP#01", Verbs.Enum.IsProvidedBy, "Baroid#01")]
        public ScalarProperty? YPLYieldStressAtMeasuredTemperatureAndPressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Nouns.Enum.ComputedData)]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.HasDynamicValue, "BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.FluidShearStress)]
        [SemanticFact("topSideTelemetry", Nouns.Enum.TopSideTelemetry)]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.IsTransmittedBy, "topSideTelemetry")]
        [SemanticFact("MovingAverageBaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.HasUncertaintyMean, "BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01")]
        [SemanticFact("YPL", Nouns.Enum.YieldPowerLaw)]
        [SemanticFact("YPL", Verbs.Enum.HasYieldPowerLawConsistencyIndex, "BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01")]
        [SemanticFact("concentricCylindersMeasurementPrinciple", Nouns.Enum.ConcentricCylindersMeasurementPrinciple)]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.UsesMeasurementPrinciple, "concentricCylindersMeasurementPrinciple")]
        [SemanticFact("BaraLogixAtActivePitYPLModelFitter#01", Nouns.Enum.ModelFitter)]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.IsComputedBy, "BaraLogixAtActivePitYPLModelFitter#01")]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.MeasurementDevice)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.HydraulicLogicalElement)]
        [SemanticFact("BaraLogixAtActivePitYPLModelFitter#01", Verbs.Enum.IsSubSystemOf, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("ActivePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Verbs.Enum.IsHydraulicConnectedTo, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredTemperature", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredTemperature")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.HasTemperatureReference, "BaraLogixAtActivePitMeasuredTemperature#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredPressure", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredPressure")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.HasPressureReference, "BaraLogixAtActivePitMeasuredPressure#01")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Baroid#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaraLogixAtActivePitYPLConsistencyIndexAtMeasuredTP#01", Verbs.Enum.IsProvidedBy, "Baroid#01")]
        public ScalarProperty? YPLConsistencyIndexAtMeasuredTemperatureAndPressure { get; set; } = null;

        [AccessToVariable(CommonProperty.VariableAccessType.Readable)]
        [Mandatory(CommonProperty.MandatoryType.General)]
        [SemanticDiracVariable("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP", Nouns.Enum.DynamicDrillingSignal)]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Nouns.Enum.ComputedData)]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.HasDynamicValue, "BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP")]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.IsOfMeasurableQuantity, BasePhysicalQuantity.QuantityEnum.DimensionLessStandard)]
        [SemanticFact("topSideTelemetry", Nouns.Enum.TopSideTelemetry)]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.IsTransmittedBy, "topSideTelemetry")]
        [SemanticFact("MovingAverageBaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Nouns.Enum.GaussianUncertainty)]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.HasUncertainty, "GaussianUncertaintyBaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01")]
        [SemanticFact("GaussianUncertaintyBaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.HasUncertaintyMean, "BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01")]
        [SemanticFact("YPL", Nouns.Enum.YieldPowerLaw)]
        [SemanticFact("YPL", Verbs.Enum.HasYieldPowerLawFlowBehaviorIndex, "BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01")]
        [SemanticFact("concentricCylindersMeasurementPrinciple", Nouns.Enum.ConcentricCylindersMeasurementPrinciple)]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.UsesMeasurementPrinciple, "concentricCylindersMeasurementPrinciple")]
        [SemanticFact("BaraLogixAtActivePitYPLModelFitter#01", Nouns.Enum.ModelFitter)]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.IsComputedBy, "BaraLogixAtActivePitYPLModelFitter#01")]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.MeasurementDevice)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Nouns.Enum.HydraulicLogicalElement)]
        [SemanticFact("BaraLogixAtActivePitYPLModelFitter#01", Verbs.Enum.IsSubSystemOf, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("ActivePitLogical#01", Nouns.Enum.ActivePitLogical)]
        [SemanticFact("BaraLogixAtActivePitMeasurementDevice#01", Verbs.Enum.IsHydraulicConnectedTo, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.TemperatureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredTemperature", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredTemperature")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.HasTemperatureReference, "BaraLogixAtActivePitMeasuredTemperature#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.Measurement)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Nouns.Enum.ContinuousDataType)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsOfMeasurableQuantity, DrillingPhysicalQuantity.QuantityEnum.PressureDrilling)]
        [SemanticFact("MovingAverageBaraLogixAtActivePitMeasuredPressure", Nouns.Enum.MovingAverage)]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsTransformationOutput, "MovingAverageBaraLogixAtActivePitMeasuredPressure")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsMeasuredBy, "BaraLogixAtActivePitMeasurementDevice#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsHydraulicallyLocatedAt, "ActivePitLogical#01")]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.HasPressureReference, "BaraLogixAtActivePitMeasuredPressure#01")]
        [SemanticFact("topOfStringJunction#01", Nouns.Enum.TopOfStringJunction)]
        [SemanticFact("inletHydraulicBranch#01", Nouns.Enum.HydraulicBranch)]
        [SemanticFact("topOfStringJunction#01", Verbs.Enum.HasUpstreamBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredTemperature#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("BaraLogixAtActivePitMeasuredPressure#01", Verbs.Enum.IsAssociatedToHydraulicBranch, "inletHydraulicBranch#01")]
        [SemanticFact("Baroid#01", Nouns.Enum.InstrumentationCompany)]
        [SemanticFact("BaraLogixAtActivePitYPLFlowBehaviorIndexAtMeasuredTP#01", Verbs.Enum.IsProvidedBy, "Baroid#01")]
        public ScalarProperty? YPLFlowBehaviorIndexAtMeasuredTemperatureAndPressure { get; set; } = null;

    }
}
